title: Estoniyada Yaşamaq Bələdçisi
description: Azərbaycanlılar üçün Estoniya həyatı üzrə praktik məsləhətlər
show_downloads: false 
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
